before_build:
  - cmd: ren EasyCrypto.Core.sln EasyCrypto.Core._sln
  - nuget restore
branches:
  only:
    - master
build:
  project: EasyCrypto.sln
  verbosity: minimal
image: Visual Studio 2015
configuration: Release
test:
  assemblies: 
    - EasyCrypto.Tests.dll